### ISSUE TITLE
The link to the Codeman Discord bot website from melee.tv/discord doesn't work anymore. Upon research, the bot is no longer online/working so the link should be removed now.

### ISSUE THREAD

**Issue by RyanMadsen** [davidvkimball/blippi#3]
The link to the [Codeman Discord bot website](https://codeman.info/) from [https://melee.tv/discord](https://melee.tv/discord) doesn't work anymore. Upon research, the bot is no longer online/working so the link should be removed now.
![image](https://github.com/user-attachments/assets/32f34a7c-1f7b-4c2a-9ca7-052d1813ab53)

**Comment by davidvkimball** [comment]
Thanks, Codeman removed.
